### ISSUE TITLE
Parser exception when using release links

### ISSUE THREAD

**Issue by bergo** [vdhicts/keepachangelog-parser#3]
Hi,

when using links for releases the parser breaks.

## Reproduction

Using links at the bottom of the changelog, like in documentation described, the parser throws a exception:

bottom of CHANGELOG.md - e.g.

`[0.3.0]: https://link-to-release`

If i remove the links, the parser works.

## Expected behavior

Exception: DOMXPath::query(): Invalid predicate
Vdhicts\KeepAChangelog\ Parser: 61

**Comment by dvdheiden** [comment]
Just released a new version in which this issue should be fixed!

**Comment by bergo** [comment]
Thank you, it works!
